---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gastown-gastown-io-v1alpha1-polecat
  failurePolicy: Fail
  name: mpolecat.kb.io
  rules:
  - apiGroups:
    - gastown.gastown.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - polecats
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gastown-gastown-io-v1alpha1-rig
  failurePolicy: Fail
  name: mrig.kb.io
  rules:
  - apiGroups:
    - gastown.gastown.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rigs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gastown-gastown-io-v1alpha1-polecat
  failurePolicy: Fail
  name: vpolecat.kb.io
  rules:
  - apiGroups:
    - gastown.gastown.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - polecats
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gastown-gastown-io-v1alpha1-rig
  failurePolicy: Fail
  name: vrig.kb.io
  rules:
  - apiGroups:
    - gastown.gastown.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rigs
  sideEffects: None
