# Community Edition deployment overlay
# For vanilla Kubernetes environments
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gastown-operator-system

resources:
- ../../default

images:
- name: controller
  newName: gastown-operator
  newTag: latest
