apiVersion: gastown.gastown.io/v1alpha1
kind: Rig
metadata:
  labels:
    app.kubernetes.io/name: gastown-operator
    app.kubernetes.io/managed-by: kustomize
  name: rig-sample
spec:
  gitURL: "git@github.com:example/myproject.git"
  beadsPrefix: "mp"
  localPath: "/workspaces/myproject"
  settings:
    namepoolTheme: "mad-max"
    maxPolecats: 8
