apiVersion: gastown.gastown.io/v1alpha1
kind: Convoy
metadata:
  labels:
    app.kubernetes.io/name: gastown-operator
    app.kubernetes.io/managed-by: kustomize
  name: convoy-sample
spec:
  # TODO(user): Add fields here
